suppressPackageStartupMessages(library(usethis))

# sort(common_packages_installed) %>% unique() %>% as.data.frame() %>% write_csv("packages.csv", quote = "all", eol = ",\n", col_names = FALSE)
# file.edit("packages.csv")

common_packages_installed <- c(
  "alluvial",
  "archivist",
  "argparser",
  "arulesViz",
  "autostsm",
  "autotest",
  "available",
  "aweSOM",
  "baseballr",
  "blastula",
  "bayesforecast",
  "bbplot",
  "beepr",
  "bench",
  "bigparallelr",
  "blob",
  "bookdown",
  "boomer",
  "bootstraplib",
  "bs4dash",
  "bslib",
  "bupaR",
  "cachem",
  "Cairo",
  "calendR",
  "camcorder",
  "capsule",
  "caret",
  "chremote",
  "chronicler",
  "circletyper",
  "circlize",
  "circularEV",
  "cli",
  "compare",
  "config",
  "configr",
  "conflicted",
  "CopSens",
  "corrmorant",
  "cowplot",
  "crossvalidation",
  "cssparser",
  "curl",
  "customLayout",
  "d3r",
  "data.table",
  "DataExplorer",
  "dataMaid",
  "datapasta",
  "datawizard",
  "DBI",
  "dbplot",
  "dbplyr",
  "devtools",
  "DiagrammeR",
  "DiagrammeRsvg",
  "diffdf",
  "diffviewer",
  "diffobj",
  "dlookr",
  "dotenv",
  "dplyr",
  "dplyr.snowflakedb",
  "DT",
  "dtw",
  "dtts",
  "dygraphs",
  "dyn.log",
  "easyalluvial",
  "edeaR",
  "emoGG",
  "emoji",
  "esquisse",
  "eventdataR",
  "extrafont",
  "exactextractr",
  "fable",
  "fable.prophet",
  "facetscales",
  "familiar",
  "fastmap",
  "fastTopics",
  "feasts",
  "ffsimulator",
  "findInFiles",
  "fixtuRes",
  "flexdashboard",
  "flextable",
  "fmsb",
  "fontawesome",
  "forcats",
  "forceR",
  "forecast",
  "formatters",
  "fpp3",
  "fs",
  "FunnelPlotR",
  "fusen",
  "future",
  "garma",
  "geofacet",
  "geojsonsf",
  "ggalluvial",
  "GGally",
  "ggalt",
  "gganatogram",
  "gganimate",
  "ggannotate",
  "ggbeeswarm",
  "ggbillboard",
  "ggblur",
  "ggbump",
  "ggbraid",
  "ggchangepoint",
  "ggcharts",
  "ggchicklet",
  "ggcor",
  "ggcounty",
  "ggCyberPunk",
  "ggdag",
  "ggdark",
  "ggdendro",
  "ggdist",
  "ggeasy",
  "ggeconodist",
  "ggedit",
  "ggeffects",
  "ggExtra",
  "ggfittext",
  "ggflags",
  "ggfocus",
  "ggforce",
  "ggformula",
  "ggfortify",
  "gggibbous",
  "ggh4x",
  "gghalves",
  "gghighlight",
  "ggimage",
  "ggimg",
  "ggip",
  "ggiraph",
  "ggkeyboard",
  "gglaplot",
  "gglm",
  "ggmacc",
  "ggmap",
  "ggmice",
  "ggmosaic",
  "ggmulti",
  "ggnewscale",
  "ggpage",
  "ggparliament",
  "ggparty",
  "ggpattern",
  "ggplot2",
  "ggpointdensity",
  "ggpol",
  "ggpolypath",
  "ggpomological",
  "ggpubr",
  "ggpval",
  "ggradar",
  "ggRandomForest",
  "ggraph",
  "ggrastr",
  "ggrepel",
  "ggridges",
  "ggrough",
  "ggsci",
  "ggsignif",
  "ggsn",
  "ggsoccer",
  "ggspatial",
  "ggspectra",
  "ggstatsplot",
  "ggstream",
  "ggsubseries",
  "ggtech",
  "ggtext",
  "ggtextures",
  "ggthemes",
  "ggthemr",
  "ggthreed",
  "ggTimeSeries",
  "ggtrack",
  "ggtree",
  "ggtrendline",
  "ggupset",
  "ggvenn",
  "ggVennDiagram",
  "ggvis",
  "ggwaffle",
  "ggweekly",
  "ggwordcloud",
  "git2r",
  "git4r",
  "glmnet",
  "glue",
  "golem",
  "gplots",
  "grid",
  "gt",
  "gtExtras",
  "hablar",
  "here",
  "hereR",
  "heuristicsmineR",
  "hrbrthemes",
  "html5",
  "htmlwidgets",
  "httr2",
  "huxtable",
  "igraph",
  "igraphdata",
  "imager",
  "incidentally",
  "influential",
  "inspectdf",
  "inspectr",
  "janitor",
  "jsonlite",
  "jtools",
  "kableExtra",
  "keras",
  "KeyboardSimulator",
  "kitten",
  "KMunicate",
  "knitcitations",
  "knitr",
  "languageserver",
  "lattice",
  "leaflegend",
  "leaflet",
  "lindia",
  "listcompr",
  "listr",
  "logr",
  "lubridate",
  "magick",
  "magrittr",
  "makepipe",
  "mailmerge",
  "mdthemes",
  "memoise",
  "memuse",
  "messydates",
  "MetBrewer",
  "metR",
  "metrica",
  "Microsoft365R",
  "mlr",
  "modeldb",
  "modeltime",
  "modeltime.gluonts",
  "moderndive",
  "mschart",
  "naniar",
  "neo4r",
  "networkscaleup",
  "networktree",
  "ngboostForecast",
  "nodbi",
  "node2vec",
  "odbc",
  "officer",
  "opencv",
  "openssl",
  "overviewR",
  "packrat",
  "padr",
  "pagedown",
  "pagedreport",
  "paletteer",
  "panelView",
  "parallelly",
  "parallelPlot",
  "parsermd",
  "parsnip",
  "parttree",
  "partykit",
  "patchwork",
  "petrinetR",
  "picker",
  "pins",
  "plotly",
  "plyr",
  "pm4py",
  "pointblank",
  "preferably",
  "prettydoc",
  "processanimateR",
  "processmapR",
  "processmonitR",
  "proffer",
  "profvis",
  "progress",
  "progressR",
  "ProjectTemplate",
  "prompter",
  "prophet",
  "purrr",
  "qcc",
  "qrencoder",
  "queuecomputer",
  "r2d3",
  "radiant",
  "ragg",
  "randomForest",
  "RandomForestsGLS",
  "rapidoc",
  "raybonsai",
  "rayimage",
  "raymolecule",
  "rayrender",
  "rayshader",
  "rayvertex",
  "rconfig",
  "RColorBrewer",
  "RCurl",
  "Rd2roxygen",
  "RPostgres",
  "reactablefmtr",
  "reactor",
  "readr",
  "readxl",
  "redoc",
  "recipies",
  "remotes",
  "renv",
  "reprex",
  "report",
  "reshape2",
  "revealjs",
  "rfm",
  "rgl",
  "RInno",
  "Rinterface",
  "riskmetric",
  "rmarkdown",
  "rmdformats",
  "rockthemes",
  "rsvg",
  "rtconnector",
  "rticles",
  "Rttf2p1",
  "rtweet",
  "runonce",
  "rvest",
  "rvg",
  "Rwclust",
  "saas",
  "scales",
  "sdcMicro",
  "sentiment.ai",
  "sfthemes",
  "shadr",
  "shinyipsum",
  "shiny",
  "shinyauthr",
  "shinyGizmo",
  "shinymaterial",
  "shinythemes",
  "shinyMobile",
  "ShinyQuickStarter",
  "shinysnippets",
  "shinytest",
  "shinytest2",
  "shinythemes",
  "shinyWidgets",
  "showtext",
  "sjPlot",
  "skimr",
  "skpr",
  "slackr",
  "SnowballC",
  "soilpalettes",
  "soundClass",
  "SparseVFC",
  "speakr",
  "spooky",
  "stacks",
  "stringr",
  "sugarbag",
  "survminer",
  "svglite",
  "sysfonts",
  "systemfonts",
  "tagger",
  "tarchetypes",
  "targets",
  "tensorflow",
  "terrainmeshr",
  "terrainr",
  "testthat",
  "textdata",
  "textrecipes",
  "textshaping",
  "thematic",
  "tickle",
  "tidybayes",
  "tidylog",
  "tidymodels",
  "tidypredict",
  "tidyr",
  "tidystringdist",
  "tidytuesdayR",
  "tidytext",
  "tidytera",
  "tidyverse",
  "timelineS",
  "timetk",
  "tinytest",
  "tm",
  "todor",
  "torchaudio",
  "treemapify",
  "tsfeatures",
  "tsibble",
  "tsibbledata",
  "tsibbletalk",
  "ttdo",
  "TTR",
  "ttt",
  "tuber",
  "tune",
  "tvthemes",
  "unglue",
  "UpSetVP",
  "urbnmapr",
  "urbnthemes",
  "usethis",
  "validate",
  "vcd",
  "vcr",
  "vdiffr",
  "waffle",
  "waldo",
  "webmockr",
  "webshot",
  "webshot2",
  "wesanderson",
  "whisker",
  "widyr",
  "word2vac",
  "wordcloud",
  "workflows",
  "workflowsets",
  "XeLaTeX",
  "XLConnect",
  "xgboost",
  "xesreadR",
  "xlsx",
  "xts",
  "yardstick",
  "yarrr"
)

library(devtools)
library(webshot)

# Check if packages are not installed and assign the
# names of the uninstalled packages to the variable new.pkg
new.pkg <- common_packages_installed[!(common_packages_installed %in% installed.packages())]

# If there are any packages in the list that aren't installed,

# install them
if (length(new.pkg)) {
  install.packages(new.pkg,
                   repos = "http://cran.rstudio.com",
                   dependencies = TRUE,
                   verbose = TRUE,
  )
}


webshot::install_phantomjs()
devtools::install_github("whjelmar/citihubstyle", dependencies = FALSE, type = "both")
devtools::install_github("rsquaredacademy/pkginfo", dependencies = FALSE, type = "both")
devtools::install_github("nicolewhite/RNeo4j", dependencies = FALSE, type = "both")
devtools::install_github("Tony-Chen-Melbourne/bcggtheme", dependencies = FALSE, type = "both")
devtools::install_github("Azure/Microsoft365R", dependencies = FALSE, type = "both")
remotes::install_github("gaborcsardi/prompt", dependencies = FALSE, type = "both")
#remotes::install_github("csgillespie/rprofile", dependencies = FALSE, type = "both")
#remotes::install_github("jalvesaq/colorout", dependencies = FALSE, type = "both")
devtools::install_github("martinctc/parallaxr", dependencies = FALSE, type = "both")
devtools::install_github("milesmcbain/fnmate", dependencies = FALSE, type = "both")
devtools::install_github("milesmcbain/tflow", dependencies = FALSE, type = "both")
devtools::install_github("matbmeijer/JirAgileR", dependencies = FALSE, type = "both")
devtools::install_github("jtlandis/ggside", dependencies = FALSE, type = "both")
devtools::install_github("r-link/corrmorant", dependencies = FALSE, type = "both")
devtools::install_github("jimhester/lookup", dependencies = FALSE, type = "both")
devtools::install_github("hoehleatsu/socialroulette", dependencies = FALSE, type = "both")
devtools::install_github("yogevherz/plotme", dependencies = FALSE, type = "both")
devtools::install_github("arthurwelle/codehover", dependencies = FALSE, type = "both")
devtools::install_github("krassowski/complex-upset", dependencies = FALSE, type = "both")
devtools::install_github("mrjoh3/ggtrack", dependencies = FALSE, type = "both")
devtools::install_github("brianwdavis/quadrangle", INSTALL_opts = "--no-multiarch", dependencies = FALSE, type = "both")
devtools::install_github("ianmoran11/mmtable2", dependencies = FALSE, type = "both")
devtools::install_github("lchiffon/wordcloud2", dependencies = FALSE, type = "both")
devtools::install_github("h-a-graham/rayvista", dependencies = FALSE, type = "both")
devtools::install_github("cynkra/fledge", dependencies = FALSE, type = "both")

# install.package('remotes', dependencies = FALSE, type = "both")
remotes::install_github('coolbutuseless/cssparser', dependencies = FALSE, type = "both")
remotes::install_github('coolbutuseless/svgparser', dependencies = FALSE, type = "both")
remotes::install_github('coolbutuseless/ggsvg', dependencies = FALSE, type = "both")
remotes::install_github("adamleerich/alrtools", dependencies = FALSE, type = "both")
remotes::install_github("jthomasmock/gtExtras", dependencies = FALSE, type = "both")
remotes::install_github("EvaMaeRey/flipbookr", dependencies = FALSE, type = "both")
remotes::install_github("matt-dray/r.oguelike", dependencies = FALSE, type = "both")
remotes::install_github("hrbrmstr/ggchicklet", dependencies = FALSE, type = "both")
remotes::install_github("yjunechoe/ggtrace", dependencies = FALSE, type = "both")
remotes::install_github("hrbrmstr/pubcheck", dependencies = FALSE, type = "both")
remotes::install_github('coolbutuseless/ggsvg', dependencies = FALSE, type = "both")
remotes::install_github("thebioengineer/camcorder", dependencies = FALSE, type = "both")
remotes::install_github("mdneuzerling/exemplar", dependencies = FALSE, type = "both")
remotes::install_github("dgkf/ggpackets", dependencies = FALSE, type = "both")
# install.packages("remotes")
remotes::install_github("jthomasmock/gistillery", dependencies = FALSE, type = "both")
remotes::install_github("analythium/rconfig", dependencies = FALSE, type = "both")

update.packages(ask=FALSE)
